apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-demo-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: data-demo
  template:
    metadata:
      labels:
        app: data-demo
    spec:
      containers:
      - name: data-demo
        image: hamzaaitmouhaoualla/data-demo-api:v9.0.3
        ports:
        - containerPort: 8080




