apiVersion: v1
kind: Service
metadata:
  name: data-demo-service
spec:
  type: NodePort
  selector:
    app: data-demo
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
